#!/usr/bin/env python3
"""Generate video with FLUX 3 Video (Black Forest Labs) via the BFL API — docs.bfl.ai/flux_3/flux3_video

One endpoint, four modes, one request shape keyed by `mode`:
    POST https://api.bfl.ai/v1/flux-3-video      header  x-key: $BFL_API_KEY
    t2v            text → video                      --prompt
    i2v            images become frames (keyframes)   --image start.png [--last-frame end.png] [--keyframe 4.5:mid.png ...]
    v2v            continue a clip from its last frames --video clip.mp4   (source ≤ 15 s, ≤ 50 MB; adds 5–15 s)
    draft_enhance  full-quality re-render of a --draft result   --enhance draft.mp4  (uses the cached bundle, same seed/inputs)
Tools:
    --upscale clip.mp4   POST /v1/flux-tools/video-upscale-v1  (1.5–3×, first 20 s, source ≤ 2560×1440, ≤ 50 MB)
    --download <id>      recover a finished result by task id (no new generation)
    --credits            print the account balance

Everything is asynchronous: submit → {id, polling_url, cost} → poll until status "Ready" → download result.sample.
Local files are sent inline as base64 (no S3 / upload step needed). Result URLs expire after ~2 h — the script
downloads immediately and writes a sidecar `<output>.json` (task id, mode, params, cost in credits, draft-cache path).

Usage:
    source ~/config.env   # BFL_API_KEY

    # Image-to-video from a storyboard still (most common). Prompt = the CHANGE + camera + audio, not the subject.
    python scripts/generate_video_flux.py --prompt "Use this image as the first frame. Camera holds locked. ..." \
        --image storyboard/scene_01.png --duration 8 --output clips/scene_01.mp4

    # Draft first (~⅓ cost, fast), then enhance the keeper at full quality / fhd — same generation, no re-roll
    python scripts/generate_video_flux.py --prompt "..." --image s.png --duration 8 --draft --output drafts/s.mp4
    python scripts/generate_video_flux.py --enhance drafts/s.mp4 --resolution fhd --output clips/s.mp4

    # Text-to-video, vertical, fhd, 12 s, silent
    python scripts/generate_video_flux.py --prompt "..." --ratio 9:16 --resolution fhd --duration 12 --no-audio --output clip.mp4

    # First + last frame (morph / land on a packshot)
    python scripts/generate_video_flux.py --prompt "..." --image a.png --last-frame b.png --duration 6 --output clip.mp4

    # Middle keyframes spaced evenly by the API (needs --image, --last-frame and --duration)
    python scripts/generate_video_flux.py --prompt "..." --image a.png --mid-image b.png --mid-image c.png --last-frame d.png --duration 12 --output clip.mp4

    # Timed keyframes  seconds:file  (up to 10 images; --duration required)
    python scripts/generate_video_flux.py --prompt "a seed grows into a tree through the seasons" \
        --keyframe 0:seed.png --keyframe 4.5:sapling.png --keyframe 10:tree.png --duration 10 --output tree.mp4

    # Continue a clip (v2v)
    python scripts/generate_video_flux.py --prompt "Continue the reference video from its final frames. She ..." \
        --video clips/scene_01.mp4 --duration 8 --output clips/scene_01_ext.mp4

    # Upscale toward 4K (creativity 0 = faithful, 1 = enhance detail)
    python scripts/generate_video_flux.py --upscale clips/s.mp4 --upscale-factor 2 --creativity 0 --output clips/s_4k.mp4

Notes:
    - Duration: whole seconds 5–20 (v2v 5–15) or "auto" (default). 24 fps. hd ≈ 720p class, fhd ≈ 1080p (1920×1088 at 16:9).
    - Aspect: auto | 21:9 | 2:1 | 16:9 | 4:3 | 1:1 | 3:4 | 9:16. Match your stills to the output aspect.
    - Audio is generated by default (dialogue, ambience, effects, music) — say what you want or pass --no-audio.
    - Cost (Sept 2026, per second of output): t2v/i2v hd $0.17 · fhd $0.29 · draft $0.06 · v2v hd $0.43 · fhd $0.54 · draft $0.12.
      The API bills in credits (1 credit ≈ $0.01); the settled figure is written to the sidecar.
    - safety_tolerance 0–4 (default 2). Keep 2 for brand work.
"""
import argparse
import base64
import json
import mimetypes
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

API = "https://api.bfl.ai/v1"
VIDEO_PATH = "/flux-3-video"
UPSCALE_PATH = "/flux-tools/video-upscale-v1"
ASPECTS = ["auto", "21:9", "2:1", "16:9", "4:3", "1:1", "3:4", "9:16"]
RES_ALIASES = {"hd": "hd", "720p": "hd", "720": "hd", "fhd": "fhd", "1080p": "fhd", "1080": "fhd"}
TERMINAL_BAD = ("Error", "Request Moderated", "Content Moderated", "Task not found")
RATES_USD_PER_S = {  # docs.bfl.ai/flux_3/flux3_overview, Sept 2026 — for the estimate line only
    ("t2v", "hd"): 0.17, ("t2v", "fhd"): 0.29, ("t2v", "draft"): 0.06,
    ("i2v", "hd"): 0.17, ("i2v", "fhd"): 0.29, ("i2v", "draft"): 0.06,
    ("v2v", "hd"): 0.43, ("v2v", "fhd"): 0.54, ("v2v", "draft"): 0.12,
}


def redact(text):
    """Never let an API key reach stdout/stderr/transcripts."""
    t = str(text)
    for k in (os.environ.get("BFL_API_KEY"), os.environ.get("FLUX_API_KEY")):
        if k and len(k) > 6:
            t = t.replace(k, "***")
    return t


def die(msg, code=1):
    print(f"ERROR: {redact(msg)}", file=sys.stderr)
    sys.exit(code)


def api_key():
    key = os.environ.get("BFL_API_KEY") or os.environ.get("FLUX_API_KEY")
    if not key:
        die("BFL_API_KEY not set. Add it to ~/config.env (dashboard: https://dashboard.bfl.ai) and `source ~/config.env`.")
    return key


def http(method, url, key, body=None, timeout=600, raw=False):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("x-key", key)
    req.add_header("Accept", "application/json")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            payload = r.read()
            return payload if raw else json.loads(payload.decode())
    except urllib.error.HTTPError as e:
        try:
            err = e.read().decode()
        except Exception:
            err = ""
        raise RuntimeError(redact(f"HTTP {e.code} {url.split('?')[0]}: {err[:1200]}")) from e
    except (urllib.error.URLError, OSError, ValueError) as e:  # DNS/TLS/timeout/bad JSON
        raise RuntimeError(redact(f"{method} {url.split('?')[0]} failed: {e}")) from e


def download(url, out_path, timeout=900):
    req = urllib.request.Request(url, method="GET")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r, open(out_path, "wb") as f:
            while True:
                chunk = r.read(1024 * 512)
                if not chunk:
                    break
                f.write(chunk)
    except (urllib.error.URLError, OSError) as e:
        raise RuntimeError(redact(f"download failed ({url.split('?')[0]}): {e}")) from e


def media_arg(path_or_url, label, max_mb=None):
    """http(s) URLs pass through; local files are read and base64-encoded (the API accepts either)."""
    if not path_or_url:
        return None
    if re.match(r"^https?://", path_or_url, re.I):
        return path_or_url
    if not os.path.exists(path_or_url):
        die(f"{label} not found: {path_or_url}")
    size_mb = os.path.getsize(path_or_url) / (1024 * 1024)
    if max_mb and size_mb > max_mb:
        die(f"{label} is {size_mb:.1f} MB; the API rejects > {max_mb} MB. Re-encode: ffmpeg -i in.mp4 -c:v libx264 -crf 23 -c:a aac out.mp4")
    with open(path_or_url, "rb") as f:
        return base64.b64encode(f.read()).decode()


def ffprobe_dims(path):
    try:
        out = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height",
                              "-of", "csv=p=0", path], capture_output=True, text=True).stdout.strip()
        w, h = out.split(",")[:2]
        return int(w), int(h)
    except Exception:
        return None


def ffprobe_duration(path):
    try:
        out = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", path],
                             capture_output=True, text=True).stdout.strip()
        return float(out) if out else None
    except Exception:
        return None


def parse_duration(s, mode):
    if s is None or str(s).lower() == "auto":
        return "auto"
    try:
        d = int(s)
    except ValueError:
        die("--duration must be a whole number of seconds or 'auto'")
    hi = 15 if mode == "v2v" else 20
    if not 5 <= d <= hi:
        die(f"--duration must be 5–{hi} s for {mode} (got {d})")
    return d


def preview_body(body):
    """Body for logs: base64 blobs replaced by their size."""
    def short(v):
        if isinstance(v, str) and re.match(r"^https?://", v, re.I):
            return v.split("?")[0] + ("?<signed>" if "?" in v else "")
        if isinstance(v, str) and len(v) > 200:
            return f"<base64 {len(v) // 1024} KB>"
        if isinstance(v, list):
            return [short(x) for x in v]
        return v
    return {k: short(v) for k, v in body.items()}


def build_keyframes(args, duration):
    """Return the `keyframes` value: a single image, a plain list, or [[seconds, image], ...]."""
    timed = []
    for kf in args.keyframe:
        if ":" not in kf:
            die(f"--keyframe expects seconds:file (got {kf})")
        t, path = kf.split(":", 1)
        try:
            t = float(t)
        except ValueError:
            die(f"--keyframe time must be a number (got {t})")
        if t < 0:
            die(f"--keyframe time must be >= 0 (got {t})")
        timed.append((t, media_arg(path, "keyframe")))
    start = media_arg(args.image, "image")
    end = media_arg(args.last_frame, "last frame")
    mids = [media_arg(m, "mid image") for m in args.mid_image]
    if mids and timed:
        die("use either --mid-image (evenly spaced) or --keyframe SEC:FILE (timed), not both")
    if mids and not (start and end):
        die("--mid-image needs both --image (first frame) and --last-frame so the API can space the middle frames evenly")

    if timed or (end and not start):
        # timed form: [[seconds, image], ...] in time order; last-frame pins to the duration
        if start:
            timed.append((0.0, start))
        if end:
            if duration == "auto":
                die("--last-frame needs --duration when used with --keyframe (or without --image) so it can be pinned to the end")
            timed.append((float(duration), end))
        timed.sort(key=lambda p: p[0])
        times = [p[0] for p in timed]
        if len(set(times)) != len(times):
            die(f"keyframe times must be unique (got {times})")
        if duration != "auto" and times[-1] > duration:
            die(f"keyframe at {times[-1]} s is beyond --duration {duration}")
        if len(timed) > 10:
            die("max 10 keyframes")
        return [[t, img] for t, img in timed]

    plain = [x for x in [start] + mids + [end] if x]
    if not plain:
        return None
    if len(plain) > 10:
        die("max 10 keyframes")
    if len(plain) >= 3 and duration == "auto":
        die("3+ plain keyframes need an explicit --duration (the API spreads the middle frames evenly across it)")
    return plain[0] if len(plain) == 1 else plain


def submit_and_wait(path, body, key, timeout_s, poll_s=3.0):
    t0 = time.time()
    # 429 = concurrency cap (a low credit balance caps active tasks at 1 per organisation) → wait and resubmit
    for attempt in range(40):
        try:
            res = http("POST", f"{API}{path}", key, body, timeout=300)
            break
        except RuntimeError as e:
            if "HTTP 429" in str(e) and time.time() - t0 < timeout_s:
                if attempt == 0:
                    print("  429 from BFL (active-task cap / rate limit) — waiting for a free slot...")
                time.sleep(15)
                continue
            raise
    task_id, poll_url = res.get("id"), res.get("polling_url")
    if not task_id:
        die(f"no task id in response: {json.dumps(res)[:800]}")
    est = res.get("cost")
    print(f"  task {task_id}" + (f" | quoted cost {est} credits (≈ ${est / 100:.2f})" if isinstance(est, (int, float)) else ""))
    poll_url = poll_url or f"{API}/get_result?id={urllib.parse.quote(task_id)}"
    last = None
    while True:
        time.sleep(poll_s)
        r = http("GET", poll_url, key, timeout=60)
        status = r.get("status")
        prog = r.get("progress")
        line = f"  [{int(time.time() - t0):4d}s] {status}" + (f" {prog * 100:.0f}%" if isinstance(prog, (int, float)) and prog <= 1 else "")
        if line != last:
            print(line)
            last = line
        if status == "Ready":
            r["_task_id"] = task_id
            r["_elapsed"] = round(time.time() - t0, 1)
            r["_quoted_cost"] = est
            return r
        if status in TERMINAL_BAD:
            die(f"{status}: {json.dumps(r.get('details') or r.get('result') or r)[:1200]}")
        if time.time() - t0 > timeout_s:
            die(f"timed out after {timeout_s}s; recover later with --download {task_id}")


def find_video_url(result):
    if not isinstance(result, dict):
        return None
    for k in ("sample", "video", "video_url", "url", "output"):
        v = result.get(k)
        if isinstance(v, str) and v.startswith("http"):
            return v
        if isinstance(v, dict) and isinstance(v.get("url"), str):
            return v["url"]
    for v in result.values():
        if isinstance(v, str) and v.startswith("http") and ".mp4" in v.split("?")[0]:
            return v
    return None


def save_result(r, args, meta):
    result = r.get("result") or {}
    url = find_video_url(result)
    task_id = r.get("_task_id")
    if not url:
        die(f"Ready but no video URL in result (task {task_id}): {json.dumps(result)[:1200]}")
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    # sidecar first: if a download fails the task id + URLs survive for --download / --draft-cache
    side = {"provider": "flux3", "task_id": task_id, "elapsed_s": r.get("_elapsed"),
            "cost_credits": r.get("cost", r.get("_quoted_cost"))}
    side.update(meta)
    side["result"] = {k: v for k, v in result.items() if not (isinstance(v, str) and len(v) > 2000)}
    dc = result.get("draft_cache")
    if isinstance(dc, str) and dc.startswith("http"):
        side["draft_cache_url"] = dc

    def write_side():
        with open(args.output + ".json", "w") as f:
            json.dump(side, f, indent=2)
    write_side()
    try:
        download(url, args.output)
    except RuntimeError as e:
        die(f"{e}\n  The generation is finished and billed; retry with: --download {task_id} --output {args.output} (URL valid ~2 h)")
    side["output_duration_s"] = ffprobe_duration(args.output)
    if isinstance(dc, str) and dc.startswith("http"):
        bin_path = args.output + ".draft_cache.bin"
        try:
            download(dc, bin_path)
            side["draft_cache_file"] = bin_path
        except RuntimeError as e:  # keep the URL at least (expires ~2 h)
            print(f"  WARN could not download draft cache: {redact(e)}")
    write_side()
    size_mb = os.path.getsize(args.output) / 1e6
    cost = side.get("cost_credits")
    cost_s = f" | {cost} credits ≈ ${cost / 100:.2f}" if isinstance(cost, (int, float)) else ""
    dur = side.get("output_duration_s")
    print(f"SAVED {args.output} ({size_mb:.1f} MB{', ' + format(dur, '.1f') + ' s' if dur else ''}) in {side['elapsed_s']}s{cost_s} | task {side['task_id']}")
    if side.get("draft_cache_file"):
        print(f"  Enhance with: --enhance {args.output} --resolution fhd --output <final.mp4>")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--prompt", default=None, help="Camera + action + light + audio, as prose. Required for t2v/i2v/v2v")
    p.add_argument("--output", default=None, help="Output .mp4 (required except --credits)")
    p.add_argument("--mode", default=None, choices=["t2v", "i2v", "v2v", "draft_enhance"], help="Force the mode (auto-detected)")
    # i2v inputs
    p.add_argument("--image", default=None, help="First-frame image (local file or URL)")
    p.add_argument("--last-frame", default=None, help="Last-frame image (needs --duration unless paired with --image only)")
    p.add_argument("--keyframe", action="append", default=[], metavar="SEC:FILE", help="Timed keyframe, repeatable (max 10 images total)")
    p.add_argument("--mid-image", action="append", default=[], metavar="FILE", help="Untimed middle keyframe(s) between --image and --last-frame; the API spaces them evenly (needs --duration)")
    # v2v / enhance / upscale
    p.add_argument("--video", default=None, help="Video to continue (v2v): ≤ 15 s, ≤ 50 MB, local or URL")
    p.add_argument("--enhance", default=None, help="A --draft output (.mp4) to re-render at full quality via its sidecar's draft cache")
    p.add_argument("--draft-cache", default=None, help="Draft-cache .bin file or URL (alternative to --enhance)")
    p.add_argument("--upscale", default=None, help="Video to upscale 1.5–3× (flux-tools/video-upscale-v1)")
    p.add_argument("--upscale-factor", type=float, default=2.0)
    p.add_argument("--creativity", type=int, default=1, choices=[0, 1], help="upscale: 0 faithful, 1 detail enhancement")
    # output controls
    p.add_argument("--ratio", default="auto", choices=ASPECTS, help="Aspect ratio (default auto)")
    p.add_argument("--resolution", default=None, help="hd (720p class, default) | fhd (1080p class; default for --enhance)")
    p.add_argument("--duration", default="auto", help="Whole seconds 5–20 (v2v 5–15) or auto")
    p.add_argument("--no-audio", action="store_true", help="Silent output (audio is generated by default)")
    p.add_argument("--draft", action="store_true", help="Fast preview at ~⅓ cost; saves a draft cache for --enhance")
    p.add_argument("--safety", type=int, default=None, choices=[0, 1, 2, 3, 4], help="safety_tolerance (default 2)")
    p.add_argument("--timeout", type=int, default=1800, help="Max seconds to wait (default 1800)")
    p.add_argument("--skip-existing", action="store_true")
    p.add_argument("--dry-run", action="store_true", help="Print the request body (media as sizes) and exit; no API call")
    # utilities
    p.add_argument("--download", default=None, help="Recover a finished result by task id")
    p.add_argument("--credits", action="store_true", help="Print account credits and exit")
    args = p.parse_args()

    if args.credits:
        if args.dry_run:
            print(f"DRY RUN: would GET {API}/credits")
            return
        key = api_key()
        print(json.dumps(http("GET", f"{API}/credits", key), indent=2))
        return
    if not args.output:
        die("--output is required")
    if args.skip_existing and os.path.exists(args.output):
        print(f"SKIP {args.output} (exists)")
        return

    if args.download:
        if args.dry_run:
            print(f"DRY RUN: would GET {API}/get_result?id={args.download} and save result.sample to {args.output}")
            return
        key = api_key()
        r = http("GET", f"{API}/get_result?id={urllib.parse.quote(args.download)}", key)
        if r.get("status") != "Ready":
            die(f"task {args.download} is {r.get('status')}: {json.dumps(r.get('details') or {})[:600]}")
        r["_task_id"] = args.download
        r["_elapsed"] = 0
        save_result(r, args, {"mode": "download"})
        return

    key = None if args.dry_run else api_key()
    res = RES_ALIASES.get((args.resolution or "").lower()) if args.resolution else None
    if args.resolution and not res:
        die("--resolution must be hd | fhd (or 720p | 1080p)")

    # ---- upscale tool
    if args.upscale:
        if not 1.5 <= args.upscale_factor <= 3.0:
            die(f"--upscale-factor must be between 1.5 and 3 (got {args.upscale_factor})")
        if not re.match(r"^https?://", args.upscale, re.I):
            d = ffprobe_duration(args.upscale)
            if d and d > 20.5:
                die(f"--upscale source is {d:.1f} s; the tool upscales only the first 20 s and rejects clips well over. Trim: ffmpeg -i in.mp4 -t 20 -c copy out.mp4")
            dims = ffprobe_dims(args.upscale)
            if dims and (dims[0] > 2560 or dims[1] > 1440 or dims[0] * dims[1] > 3_700_000):
                die(f"--upscale source is {dims[0]}x{dims[1]}; max 2560x1440 (3.7 MP). Downscale first: ffmpeg -i in.mp4 -vf scale=1920:-2 out.mp4")
        body = {"input_video": media_arg(args.upscale, "video", max_mb=50), "creativity": args.creativity,
                "upscale_factor": args.upscale_factor}
        if args.prompt:
            body["prompt"] = args.prompt
        if args.safety is not None:
            body["safety_tolerance"] = args.safety
        print(f"Submitting FLUX 3 upscale ×{args.upscale_factor} | {args.upscale}")
        if args.dry_run:
            print(json.dumps(preview_body(body), indent=2))
            return
        try:
            r = submit_and_wait(UPSCALE_PATH, body, key, args.timeout)
        except RuntimeError as e:
            die(str(e))
        save_result(r, args, {"mode": "upscale", "source": args.upscale, "upscale_factor": args.upscale_factor,
                              "creativity": args.creativity, "prompt": args.prompt})
        return

    # ---- draft enhance
    if args.enhance or args.draft_cache or args.mode == "draft_enhance":
        cache = None
        src = args.draft_cache
        if args.enhance and not src:
            side_path = args.enhance + ".json"
            if not os.path.exists(side_path):
                die(f"no sidecar {side_path}; pass --draft-cache <file.bin|url> instead")
            try:
                with open(side_path) as f:
                    side = json.load(f)
            except (OSError, ValueError) as e:
                die(f"cannot read sidecar {side_path}: {e}")
            if not isinstance(side, dict):
                die(f"sidecar {side_path} is not a JSON object")
            src = side.get("draft_cache_file") or side.get("draft_cache_url")
            if not src:
                die(f"{side_path} has no draft cache — was that clip generated with --draft?")
        if not src:
            die("--enhance <draft.mp4> or --draft-cache <file|url> is required for draft_enhance")
        cache = media_arg(src, "draft cache")  # URL passes through (valid ~2 h), .bin becomes base64
        body = {"mode": "draft_enhance", "draft_cache": cache, "resolution": res or "fhd"}
        if args.safety is not None:
            body["safety_tolerance"] = args.safety
        print(f"Submitting FLUX 3 draft_enhance | {body['resolution']} | cache from {src if not src.startswith('http') else 'URL'}")
        if args.dry_run:
            print(json.dumps(preview_body(body), indent=2))
            return
        try:
            r = submit_and_wait(VIDEO_PATH, body, key, args.timeout)
        except RuntimeError as e:
            die(str(e))
        save_result(r, args, {"mode": "draft_enhance", "resolution": body["resolution"], "source_draft": args.enhance,
                              "prompt": None})
        return

    # ---- t2v / i2v / v2v
    has_images = bool(args.image or args.last_frame or args.keyframe or args.mid_image)
    mode = args.mode
    if not mode:
        if args.video and has_images:
            die("--video (continuation) and --image/--keyframe (image-to-video) cannot be combined; FLUX 3 has no image-guided continuation")
        if args.video:
            mode = "v2v"
        elif has_images:
            mode = "i2v"
        else:
            mode = "t2v"
    else:  # forced mode must not silently drop inputs the user passed (each call is billed)
        if mode == "t2v" and (has_images or args.video):
            die("--mode t2v ignores --image/--keyframe/--video; drop the inputs or the --mode flag")
        if mode == "i2v" and args.video:
            die("--mode i2v cannot take --video; use --mode v2v (continuation) or drop --video")
        if mode == "v2v" and has_images:
            die("--mode v2v cannot take --image/--keyframe; continuation is driven by the source clip only")
    if not args.prompt:
        die(f"--prompt is required for {mode}")
    duration = parse_duration(args.duration, mode)

    body = {"mode": mode, "prompt": args.prompt}
    if args.ratio != "auto":
        body["aspect_ratio"] = args.ratio
    if duration != "auto":
        body["duration"] = duration
    if res:
        body["resolution"] = res
    if args.no_audio:
        body["generate_audio"] = False
    if args.draft:
        body["draft"] = True
    if args.safety is not None:
        body["safety_tolerance"] = args.safety

    if mode == "i2v":
        kf = build_keyframes(args, duration)
        if kf is None:
            die("i2v needs --image, --last-frame or --keyframe")
        body["keyframes"] = kf
    elif mode == "v2v":
        if not args.video:
            die("v2v needs --video")
        src_dur = ffprobe_duration(args.video) if not args.video.startswith("http") else None
        if src_dur and src_dur > 15.05:
            die(f"--video is {src_dur:.1f} s; v2v sources must be ≤ 15 s (trim: ffmpeg -i in.mp4 -t 15 -c copy out.mp4)")
        body["start_video"] = media_arg(args.video, "video", max_mb=50)
        if not re.search(r"continu|pick(s|ing)? up|from (its|the) (final|last) frame", args.prompt, re.I):
            print("  NOTE: v2v prompts work best when they open with \"Continue the reference video from its final frames. ...\"")

    est_rate = RATES_USD_PER_S.get((mode, "draft" if args.draft else (res or "hd")))
    est = f" | ≈ ${est_rate * duration:.2f} est." if est_rate and duration != "auto" else ""
    kf_desc = ""
    if mode == "i2v":
        kf = body["keyframes"]
        kf_desc = " | 1 keyframe" if isinstance(kf, str) else f" | {len(kf)} keyframes" + (" (timed)" if isinstance(kf[0], list) else "")
    dur_s = "auto" if duration == "auto" else f"{duration}s"
    print(f"Submitting FLUX 3 {mode} | {args.ratio} {res or 'hd'} | {dur_s}{' | draft' if args.draft else ''}"
          f"{' | silent' if args.no_audio else ''}{kf_desc}{est}")
    print(f"  Prompt: {args.prompt[:140]}{'...' if len(args.prompt) > 140 else ''}")
    if args.dry_run:
        print(json.dumps(preview_body(body), indent=2))
        return
    try:
        r = submit_and_wait(VIDEO_PATH, body, key, args.timeout)
    except RuntimeError as e:
        die(str(e))
    meta = {"mode": mode, "prompt": args.prompt, "aspect_ratio": args.ratio, "resolution": res or "hd", "duration": duration,
            "draft": args.draft, "audio": not args.no_audio,
            "inputs": {"image": args.image, "last_frame": args.last_frame, "mid_images": args.mid_image, "keyframes": args.keyframe, "video": args.video}}
    save_result(r, args, meta)


if __name__ == "__main__":
    main()
